# Generated by Django 3.0.3 on 2020-02-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='location',
            field=models.CharField(default='enter location...', max_length=200),
        ),
    ]
