# Generated by Django 3.0.3 on 2020-02-28 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_artist_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='location',
            field=models.CharField(default='enter location...', max_length=200),
        ),
        migrations.AddField(
            model_name='session',
            name='appointment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.PositiveIntegerField(default=30, verbose_name='minutes'),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studio',
            name='location',
            field=models.CharField(default='enter location...', max_length=200),
        ),
    ]
