# Generated by Django 3.0.3 on 2020-02-28 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20200227_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='name',
        ),
    ]
