# Generated by Django 3.0.3 on 2020-03-07 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_remove_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='artist',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Artist'),
        ),
        migrations.AddField(
            model_name='session',
            name='engineer',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Engineer'),
        ),
        migrations.AddField(
            model_name='session',
            name='studio',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Studio'),
        ),
    ]
